definitions:
  oauth_errors.SwaggerRestErr:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  token.AccessToken:
    properties:
      access_token:
        type: string
    type: object
  token.RefreshToken:
    properties:
      refresh_token:
        type: string
    type: object
  token.Token:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_id:
        type: integer
    type: object
  token.TokenClaimsResponse:
    properties:
      expires_at:
        type: integer
      issuer:
        type: string
      token_type:
        type: string
      user_id:
        type: integer
    type: object
  token.TokenRequest:
    properties:
      password:
        type: string
      scope:
        type: string
      user_email:
        description: used for password grant type
        type: string
    type: object
  token.VerifyRequest:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /oauth/create:
    post:
      consumes:
      - application/json
      description: Generate and return new access and refresh tokens with provided
        information
      parameters:
      - description: Token Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/token.TokenRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/token.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
      summary: Create new access and refresh tokens
      tags:
      - token
  /oauth/refresh:
    post:
      consumes:
      - application/json
      description: Parse refresh token and validate claims, if all is ok, generate
        new access token
      parameters:
      - description: Refresh Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/token.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/token.AccessToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
      summary: Generate new access token based on a refresh token
      tags:
      - token
  /oauth/verify:
    post:
      consumes:
      - application/json
      description: Parse token and validate claims, if all is ok, return claims
      parameters:
      - description: Verify Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/token.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/token.TokenClaimsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/oauth_errors.SwaggerRestErr'
      summary: Validate given token
      tags:
      - token
swagger: "2.0"
